export const SET_PRIMARY_STREAM = "SET_PRIMARY_STREAM";
export const REGISTER_PARTICIPANT = "REGISTER_PARTICIPANT";
export const UNREGISTER_PARTICIPANT = "UNREGISTER_PARTICIPANT";
export const SET_LOCAL_PARTICIPANT = "SET_LOCAL_PARTICIPANT";
export const UPDATE_LOCAL_PARTICIPANT = "UPDATE_LOCAL_PARTICIPANT";
export const REFRESH_PARTICIPANT = "REFRESH_PARTICIPANT";
